---
name: markdownlint

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Check for Markdown errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .github/markdownlint-config.json
          files: './*.md'
